### ISSUE TITLE
`std::sync::Once::new` is only const since Rust 1.32.0, raise MSRV to 1.34.0?

### ISSUE THREAD

**Issue by lopopolo** [strawlab/iana-time-zone#68]
`std::sync::Once::new` is only const since Rust 1.32.0, see docs: https://doc.rust-lang.org/std/sync/struct.Once.html#method.new.

Our current MSRV for tier 1 platforms is documented as Rust 1.31.0:

https://github.com/strawlab/iana-time-zone/blob/7b4ced8f57fa16305affaf3c01f18aa74c802869/README.md?plain=1#L28-L29

`Once::new` is used in const context in the Windows and Android platforms. Windows is a tier 1 platform.

https://github.com/strawlab/iana-time-zone/blob/7b4ced8f57fa16305affaf3c01f18aa74c802869/src/tz_windows.rs#L31

I'd like to use this ticket as a discussion around moderately increasing MSRV:

- Given we are already using `Once::new` in static context, we require Rust 1.32.0.
- Getting access to `TryFrom` in Rust 1.34.0 -- https://blog.rust-lang.org/2019/04/11/Rust-1.34.0.html#whats-in-1340-stable -- would lead to some easier to read code when twiddling indexes from FFI APIs, as was discussed in https://github.com/strawlab/iana-time-zone/pull/67#discussion_r983955802.

How do we feel about raising MSRV to Rust 1.34.0?

**Comment by Kijewski** [comment]
It's sad that crates.io does not give you an overview about the actually used cargo/rustc version of the downloads. Pypi is great in that regard: https://pypistats.org/packages/pyjson5. Otherwise who would have guessed that most users still seem to use the ancient Python 3.7 version from 2018-06-27?

Yes, it makes sense to bump the MSRV to 1.34 to get access to `TryFrom`. I don't think break the workflow for anyone by this change.

Windows compiles fine in 1.31: https://github.com/strawlab/iana-time-zone/actions/runs/3115036644/jobs/5051536419, though. It's odd that it does work.

**Comment by astraw** [comment]
Chrono has had an MSRV of 1.38 since 0.4.22 released two months ago. As they are by far the biggest user, I think we can safely go to 1.38.
